In [117]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.utils import shuffle
from sklearn import tree

In [118]:
imu_data = pd.read_csv("Dataset.csv")

In [119]:
imu_data.head()

-0.967307  -9.036178  -5.037657  -0.526883  -0.259014  -0.390219  \
0  -1.027165  -9.158288  -5.032868  -0.532475  -0.299228  -0.397410   
1  -0.821253  -8.988291  -4.987376  -0.560172  -0.151953  -0.334558   
2  -1.094206  -9.182231  -4.977799  -0.522888  -0.228121  -0.380099   
3  -1.084629  -9.285188  -4.688086  -0.545259  -0.332518  -0.407263   
4  -1.031954  -9.096036  -4.996953  -0.527948  -0.264340  -0.374240   

   -35.787967    42.7695  6.327892  1  
0  -35.259078  41.882167  6.156868  1  
1  -33.672420  42.414566  5.985844  1  
2  -36.316852  42.592033  5.814820  1  
3  -35.611671  42.946968  6.156868  1  
4  -36.316852  42.237102  5.814820  1

In [120]:
imu_shuffle_data = shuffle(imu_data)

In [121]:
imu_shuffle_data.head()

-0.967307  -9.036178  -5.037657  -0.526883  -0.259014  -0.390219  \
927  -9.550958  -1.189979  -2.734318   0.123812   0.098058   0.129626   
496   1.101389   9.325891  -5.808629  -0.049505  -0.038361   0.406652   
471   0.885900   9.419270  -5.820601  -0.066017  -0.107338   0.417571   
959  -9.907711  -0.835619  -2.288974   0.178940   0.079415   0.118973   
47   -1.039137  -9.081670  -4.917941  -0.511436  -0.241437  -0.380099   

     -35.787967    42.7695   6.327892  1  
927    8.109589  54.659778   1.026145  4  
496   20.273971   4.436670   8.038134  2  
471   19.921380   4.081737  10.432472  2  
959    8.638475  52.352710  -1.197169  4  
47   -35.964260  42.592033   6.156868  1

In [122]:
print ("Dataset Lenght:: "+ str(len(imu_shuffle_data)))
print ("Dataset Shape:: "+str(imu_shuffle_data.shape))

Dataset Lenght:: 1500
Dataset Shape:: (1500, 10)


In [123]:
X = imu_shuffle_data.values[:,0:9]
Y = imu_shuffle_data.values[:,-1]

In [124]:
X_train, X_test, y_train, y_test = train_test_split( X, Y, test_size = 0.3, random_state = 100)

In [125]:
clf_gini = DecisionTreeClassifier(criterion = "gini", random_state = 100,
                               max_depth=3, min_samples_leaf=5)
clf_gini.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [126]:
clf_entropy = DecisionTreeClassifier(criterion = "entropy", random_state = 100,
 max_depth=3, min_samples_leaf=5)
clf_entropy.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [127]:
clf_gini.predict([[-1.053502,-9.151105,-4.968222,-0.525817,-0.22892,-0.382496,-35.96426,42.592033,5.81482
]])

array([1.])

In [128]:
y_pred = clf_gini.predict(X_test)
y_pred

array([2., 2., 5., 2., 2., 5., 4., 1., 2., 1., 1., 2., 2., 2., 2., 2., 2.,
       5., 2., 5., 2., 2., 1., 2., 4., 2., 2., 5., 5., 2., 2., 2., 1., 2.,
       5., 4., 1., 2., 2., 2., 2., 4., 1., 4., 2., 2., 4., 5., 2., 5., 2.,
       1., 1., 2., 1., 2., 1., 5., 2., 2., 2., 5., 2., 1., 2., 5., 2., 2.,
       4., 1., 5., 5., 2., 4., 2., 2., 2., 2., 2., 4., 5., 2., 4., 2., 1.,
       5., 2., 2., 4., 4., 4., 1., 2., 5., 4., 5., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 5., 2., 1., 2., 5., 4., 2., 1., 2., 2., 5., 1., 1., 2.,
       2., 2., 2., 2., 2., 1., 2., 2., 2., 2., 4., 2., 2., 4., 2., 2., 2.,
       2., 4., 1., 1., 2., 2., 2., 1., 4., 1., 5., 1., 5., 2., 5., 2., 2.,
       2., 1., 2., 2., 2., 2., 2., 2., 5., 2., 2., 1., 2., 2., 1., 4., 1.,
       2., 4., 1., 5., 4., 5., 4., 2., 4., 5., 2., 2., 5., 5., 2., 1., 5.,
       2., 5., 1., 2., 5., 2., 2., 2., 4., 4., 2., 2., 2., 2., 1., 4., 2.,
       4., 1., 5., 2., 2., 1., 4., 2., 4., 2., 2., 2., 2., 1., 1., 2., 2.,
       2., 2., 2., 1., 2.

In [129]:
y_pred_en = clf_entropy.predict(X_test)
y_pred_en

array([6., 3., 5., 3., 3., 5., 4., 1., 2., 1., 1., 6., 3., 6., 3., 3., 3.,
       5., 2., 5., 2., 6., 1., 2., 4., 3., 2., 5., 5., 6., 6., 6., 1., 6.,
       5., 4., 1., 6., 2., 6., 2., 4., 1., 4., 2., 3., 4., 5., 3., 5., 3.,
       1., 1., 6., 1., 2., 1., 5., 2., 2., 3., 5., 6., 1., 3., 5., 3., 6.,
       4., 1., 5., 5., 2., 4., 2., 6., 6., 6., 2., 4., 5., 2., 4., 6., 1.,
       5., 3., 3., 4., 4., 4., 1., 3., 5., 4., 5., 2., 3., 2., 6., 3., 3.,
       2., 2., 2., 5., 3., 1., 2., 5., 4., 6., 1., 2., 6., 5., 1., 1., 3.,
       3., 6., 3., 6., 6., 1., 2., 6., 6., 2., 4., 6., 2., 4., 6., 6., 6.,
       6., 4., 1., 1., 6., 2., 2., 1., 4., 1., 5., 1., 5., 2., 5., 2., 6.,
       3., 1., 3., 3., 6., 3., 2., 3., 5., 3., 2., 1., 2., 6., 1., 4., 1.,
       6., 4., 1., 5., 4., 5., 4., 3., 4., 5., 6., 3., 5., 5., 2., 1., 5.,
       2., 5., 1., 6., 5., 2., 3., 2., 4., 4., 2., 2., 6., 6., 1., 4., 3.,
       4., 1., 5., 2., 3., 1., 4., 3., 4., 2., 2., 3., 2., 1., 1., 6., 3.,
       3., 2., 6., 1., 6.

In [130]:
print ("Accuracy is "+str( accuracy_score(y_test,y_pred)*100))

Accuracy is 62.22222222222222


In [131]:
print ("Accuracy is "+ str(accuracy_score(y_test,y_pred_en)*100))

Accuracy is 100.0
